version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install -g nx
      - npm ci
  build:
    commands:
      - nx run opinion-management-service:build
  post_build:
    commands:
      - cp template.yaml dist/src/opinion-management-service/
      - cd dist/src/opinion-management-service
      - zip -r ../../../function.zip .
      - cd ../../..
artifacts:
  files:
    - function.zip
    - template.yaml
  name: build_output
